spring:
  profiles:
    active: native
--- 
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations:
            file://PATH_TO_MICROSERVICES_PROJECT/subs-config-properties/{application}/{profile},
            file://PATH_TO_MICROSERVICES_PROJECT/subs-config-properties/global/{profile}
---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/adem-bench/subs-config-properties.git
          search-paths:
            - "subs-config-properties/{application}/{profile}"
            - "subs-config-properties/global/{profile}"
